server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: ${EUREKA_USERNAME:eureka}
      password: ${EUREKA_PASSWORD:eureka123}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    register-with-eureka: false      # this IS the server
    fetch-registry: false            # no need to fetch from itself
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true         # prevent ghost de-registrations
    eviction-interval-timer-in-ms: 15000   # check every 15 seconds
    expected-client-renewal-interval-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
